-- ============================================================
-- csmOS — Full Setup SQL for Supabase
-- Paste this entire file into: Dashboard → SQL Editor → New query → Run
-- ============================================================

-- ── 1. SCHEMA ────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.users (
  id            BIGSERIAL PRIMARY KEY,
  name          TEXT NOT NULL,
  email         TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role          TEXT DEFAULT 'csm',
  csm_name      TEXT,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.accounts (
  id                              BIGSERIAL PRIMARY KEY,
  account_name                    TEXT NOT NULL,
  tenant_id                       TEXT,
  industry                        TEXT,
  mrr_tier                        TEXT,
  mrr                             NUMERIC DEFAULT 0,
  region                          TEXT,
  csm_lead                        TEXT,
  csm                             TEXT,
  closure_eta                     TEXT,
  cp                              TEXT,
  tam_assigned                    TEXT,
  billing_frequency               TEXT,
  renewal_date                    TEXT,
  renewal_status                  TEXT,
  churn_status                    TEXT,
  churn_reason                    TEXT,
  renewal_comments                TEXT,
  implementation_status           TEXT,
  implementation_type             TEXT,
  ps_engagement                   TEXT,
  ps_solutioning                  TEXT,
  account_understanding_session   TEXT,
  new_csm_intro_done              TEXT,
  csm_escalation_matrix_shared    TEXT,
  ring_fence_meeting_initiated    TEXT,
  meeting_planned_date            TEXT,
  meeting_done                    TEXT,
  issue_mapping_sheet_updated     TEXT,
  review_cadence_alignment        TEXT,
  adoption_score                  NUMERIC,
  stickiness_score                NUMERIC,
  rag_status                      TEXT DEFAULT 'Green',
  rag_reason                      TEXT,
  actions_taken                   TEXT,
  contraction_risk                TEXT DEFAULT 'No',
  churn_risk                      TEXT DEFAULT 'No',
  grr                             NUMERIC,
  nps                             NUMERIC,
  adoption_rate                   NUMERIC,
  sa_status                       TEXT,
  poc1_name                       TEXT,
  poc1_email                      TEXT,
  poc1_phone                      TEXT,
  poc1_designation                TEXT,
  poc2_name                       TEXT,
  poc2_email                      TEXT,
  poc2_phone                      TEXT,
  poc2_designation                TEXT,
  poc3_name                       TEXT,
  poc3_email                      TEXT,
  poc3_phone                      TEXT,
  poc3_designation                TEXT,
  updated_at                      TIMESTAMPTZ DEFAULT NOW(),
  created_at                      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.activity_log (
  id         BIGSERIAL PRIMARY KEY,
  account_id BIGINT REFERENCES public.accounts(id) ON DELETE CASCADE,
  user_id    BIGINT REFERENCES public.users(id),
  action     TEXT,
  changes    JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_accounts_csm        ON public.accounts(csm);
CREATE INDEX IF NOT EXISTS idx_accounts_rag_status ON public.accounts(rag_status);
CREATE INDEX IF NOT EXISTS idx_accounts_industry   ON public.accounts(industry);
CREATE INDEX IF NOT EXISTS idx_accounts_region     ON public.accounts(region);
CREATE INDEX IF NOT EXISTS idx_accounts_name       ON public.accounts USING gin(to_tsvector('english', account_name));

ALTER TABLE public.users        DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.accounts     DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_log DISABLE ROW LEVEL SECURITY;

-- ── 2. USERS ─────────────────────────────────────────────────

INSERT INTO public.users (name, email, password_hash, role, csm_name) VALUES
  ('Anindya Roy',      'anindya@leadsquared.com',          '$2a$10$tTWT92kw8Gmee6V256WuXOH2T6AfX.m4AthbzNtwMQX2Iz8WhfnxO', 'admin', 'Anindya'),
  ('Abhishek Bhargav', 'abhishek.bhargav@leadsquared.com', '$2a$10$2pf.nqJVOUb/Ik6M61ZhyOm32VVEwbRsrs0np49at7fw04xSJOsje',   'csm',   'Abhishek Bhargav'),
  ('Bhoomit Ahlawat',  'bhoomit.ahlawat@leadsquared.com',  '$2a$10$2pf.nqJVOUb/Ik6M61ZhyOm32VVEwbRsrs0np49at7fw04xSJOsje',   'csm',   'Bhoomit Ahlawat'),
  ('Nikhil Chand',     'nikhil.chand@leadsquared.com',     '$2a$10$2pf.nqJVOUb/Ik6M61ZhyOm32VVEwbRsrs0np49at7fw04xSJOsje',   'csm',   'Nikhil Chand'),
  ('Vaibhav',          'vaibhav@leadsquared.com',          '$2a$10$2pf.nqJVOUb/Ik6M61ZhyOm32VVEwbRsrs0np49at7fw04xSJOsje',   'csm',   'Vaibhav'),
  ('Poorva Pandya',    'poorva.pandya@leadsquared.com',    '$2a$10$2pf.nqJVOUb/Ik6M61ZhyOm32VVEwbRsrs0np49at7fw04xSJOsje',   'csm',   'Poorva Pandya'),
  ('Amarjeet',         'amarjeet@leadsquared.com',         '$2a$10$2pf.nqJVOUb/Ik6M61ZhyOm32VVEwbRsrs0np49at7fw04xSJOsje',   'csm',   'Amarjeet')
ON CONFLICT (email) DO NOTHING;

-- ── 3. ACCOUNTS (82 rows) ────────────────────────────────────

INSERT INTO public.accounts (
  account_name, tenant_id, industry, mrr_tier, mrr, region, csm_lead, csm,
  closure_eta, cp, tam_assigned, billing_frequency, renewal_date, renewal_status,
  churn_status, churn_reason, renewal_comments, implementation_status, implementation_type,
  ps_engagement, ps_solutioning, account_understanding_session, new_csm_intro_done,
  csm_escalation_matrix_shared, ring_fence_meeting_initiated, meeting_planned_date,
  meeting_done, issue_mapping_sheet_updated, review_cadence_alignment,
  adoption_score, stickiness_score, rag_status, rag_reason, actions_taken,
  contraction_risk, churn_risk, grr, nps, adoption_rate, sa_status
) VALUES
  ('Addictive Learning Technology Pvt. Ltd', '55380', 'Edtech', 'Tier 1 (>500k)', 542600, 'North', 'Anindya', 'Abhishek Bhargav', '18-Apr-26', 'Shivam Singh', 'No', 'Half Yearly', '16/07/26', 'Renewal Pending', 'Contraction Predicted', 'ROI', 'Client has reduced team size; recent Zipteams onboarding experience was poor, and MCube''s billing structure has also contributed to client dissatisfaction and frustration.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '7/4/26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Green', 'Multiple trainings done, three champions built, automation and new requirements addressed. Zip teams and Mcube POC started.', 'Connected with client on daily basis ensuring Mcube and Zipteams adoption and issues are addressed timely.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('AKZO NOBEL INDIA LIMITED', '77353', 'Manufacturing', 'Tier 1 (>500k)', 1034000, 'North', 'Anindya', 'Bhoomit Ahlawat', '18-Apr-26', 'Anil/ Manish', 'Abhinav', 'Quarterly', '26/06/28', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '3-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Acquired by JSW; Project Build expected 30 May, PS ETA 22 June; missing PJP reports; historical data mismatch; OMS issues; batch job master sync issues.', 'Pushing PS to deliver max projects; aligned customer + PS on ETA; weekly cadence set up; PJP Reports delivered.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Alliance Infrastructure Projects Pvt Ltd', '5528', 'Real Estate', 'Tier 1 (>500k)', 1747200, 'South', 'Anindya', 'Bhoomit Ahlawat', NULL, 'Anil/ Manish', 'VLS Amrutha', 'Quarterly', '31/03/27', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'No', 'Yes', 'Yes', NULL, NULL, 'Green', 'Account stable. Well-defined single-property single-tenant use case; highly customised workflow; PS direct connect established for CRs/issues.', 'Continue weekly cadence calls to maintain Green status.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Amity University / Amity Study Abroad', '24300', 'Education', 'Tier 1 (>500k)', 1329600, 'North', 'Anindya', 'Abhishek Bhargav', '18-Apr-26', 'Shivam Singh', 'Vardhan BO', 'Quarterly', '30/01/27', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '9/4/26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'AMity C5 and Noida are green. Amity C6 is Amber due to few open pointers and ongoing projects.', 'Resolved WhatsApp/Email/SMS issues, lead stage update discrepancies, Amizone integration fixed. C6 CRs in progress with PS.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Anandilal And Ganesh Podar Society', '42246', 'Education', 'Tier 2 (300k - 500k)', 469270, 'West', 'Anindya', 'Nikhil Chand', '18-Apr-26', 'Rishit Hitesh Sheth', 'Santhosh', 'Quarterly', '29/10/28', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '7-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Cx not satisfied with Siera. Real time sync, long download time, low indexing, Siera reports not working like Logi reports.', 'Meeting set with Cx on 11th May to understand the gaps in Logi and Siera.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Apollo Healthco Limited', '65155', 'Healthcare and Wellness', 'Tier 1 (>500k)', 934394, 'South', 'Anindya', 'Amarjeet', '25-Apr-26', 'Mrinmoy Chakraborty', 'VLS Amrutha', 'Quarterly', '24/03/27', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '24/4/2026', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Delivery delays or pending implementation items are impacting customer confidence.', 'Internal teams aligned, tracker created, regular cadence initiated for closure.', 'No', 'No', 100, NULL, NULL, NULL),
  ('Bajaj Auto Pvt Ltd', '62450', 'Automotive', 'Tier 1 (>500k)', 9992518, 'West', 'Anindya', 'Nikhil Chand', '25-Apr-26', 'Anil/ Manish', 'Sai Rohith, Yogesh, Sushant', 'Monthly', '30/09/26', 'Renewal Pending', NULL, NULL, 'Meeting happened between Bajaj and LSQ in May. Product roadmap showcased. Cx raised concerns regarding competitor pricing.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '21-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Green', 'Competitor risk: Microsoft at 96 vs LSQ at 200. Contraction risk due to dual license in Chetak and MC, storage billing extra.', 'F2F meeting with Bajaj Leadership showcasing product roadmap for AI and current feasible solutions.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Beyond Odds Technologies Private Limited', '72959', 'Edtech', 'Tier 2 (300k - 500k)', 398500, 'South', 'Anindya', 'Vaibhav', '25-Apr-26', 'Anjali Jha', 'Santhosh', 'Quarterly', '3/10/27', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'No', NULL, NULL, 'Green', 'Re-implementation underway as previous setup not aligned with client''s business requirements. Stickiness is good, client adding users.', 'Re-implementation in progress. Updates to be shared on completion.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Bonito Designs Pvt Ltd', '39689', 'Real Estate', 'Tier 2 (300k - 500k)', 354520, 'South', 'Anindya', 'Bhoomit Ahlawat', NULL, 'Shikhar', 'Prakhar', 'Half Yearly', '9/12/26', 'Renewal Pending', 'Churn Activated', 'Experience', 'Churn Activated — reason Experience. Customer had poor experience with Sierra reporting, stated intent to close/not renew.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '8-May-26', 'Yes', 'Yes', 'No', NULL, NULL, 'Amber', 'Exploring other CRMs; main PoC dislikes SIERA; SIERA migration not received well; CloneDB access delayed; last month''s lead import issue.', 'F2F connect on 8 May; one dashboard live; 2nd dashboard ready once field updated.', 'No', 'Yes', 100, NULL, NULL, 'Open'),
  ('Chandigarh Educational Trust (Regd.)', '70845', 'Education', 'Tier 1 (>500k)', 709155, 'North', 'Anindya', 'Vaibhav', '18-Apr-26', 'Abhishek Kumar', 'Madhu Kumar AN', 'Quarterly', '13/09/27', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '22/04/2026', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Green', 'Multiple product issues — widget failures, system slowness, login errors causing direct business impact. 5 major incidents in last 10 days.', 'Daily connects maintained. DRM support engaged for all system issues.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Chettinad Cement Corporation Ltd', '76502', 'Manufacturing', 'Tier 2 (300k - 500k)', 344750, 'South', 'Anindya', 'Bhoomit Ahlawat', '18-Apr-26', 'Vijayakumar K', 'No', 'Quarterly', '29/01/28', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '22-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Slow response from PS and Support; cadence was issue-resolution only, no value-added conversations.', 'Working with BCG (Chettinad''s consultants) to drive value-driven LSQ usage; gathering new dashboard and form-change requirements.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('CK Birla Hospital for Women', '41989', 'Healthcare and Wellness', 'Tier 2 (300k - 500k)', 380593, 'North', 'Anindya', 'Poorva Pandya', NULL, 'Shikhar', 'No', 'Yearly', '7/8/28', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '4/2/26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'New tenant implementation delay — Reports and dashboards not delivered yet, committed go live was February.', 'PS and report team working on it. Dedicated resource to deliver by 13th May. Target go live by 15th May.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('CL Educate Limited', '6788', 'Education', 'Tier 2 (300k - 500k)', 356715, 'North', 'Anindya', 'Poorva Pandya', '4/14/26', 'Shivam Singh', 'No', 'Half Yearly', '15/09/28', 'Renewal Pending', NULL, NULL, 'Account health is green, do not see any risk.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '4/14/26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Customer wants to revisit automations, forms, processes. 70+ automations in production need careful planning.', 'Suggested to initiate off season. Customer aligned and will inform when to plan.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Comfort Grid Technologies Pvt Ltd', '72117', 'Manufacturing', 'Tier 1 (>500k)', 800000, 'West', 'Anindya', 'Nikhil Chand', '25-Apr-26', 'Anil/ Manish', 'Vardhan BO', 'Quarterly', '21/12/26', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '17-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Database storage report shows 85 GB shortage. Product outage thrice in 1 week resulting in dissatisfaction.', 'Database storage case raised with support and routed to product team for RCA.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Dayananda Sagar Academy of Technology and Management', '66406', 'Education', 'Tier 2 (300k - 500k)', 393552, 'South', 'Anindya', 'Abhishek Bhargav', '18-Apr-26', 'Vineet Pandey', 'No', 'Yearly', '29/01/27', NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', '6/4/26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Regular issues due to automation, LAPP failures causing bad sentiment. Cx needs immediate WhatsApp updates.', 'Increased API rate limit on FOC which reduced LAPP failures. Continuing support on WhatsApp group.', 'No', 'No', 96, NULL, NULL, NULL),
  ('DELHIVERY LIMITED', '69474', 'Logistics', 'Tier 1 (>500k)', 513750, 'North', 'Anindya', 'Bhoomit Ahlawat', '18-Apr-26', 'Rishit Hitesh Sheth', 'Amit', 'Quarterly', '23/06/26', 'Renewed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '9-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'No weekly/biweekly cadence prior; no download on new LSQ offerings; delayed responses from PS, Support and KAM teams.', 'Solved all customer points via tracker; ran product download meeting with senior leadership; set up monthly review meeting.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Doctutorials Edutech Pvt Ltd', '62521', 'Edtech', 'Tier 1 (>500k)', 528928, 'South', 'Anindya', 'Amarjeet', '25-Apr-26', 'Anjali Jha', 'No', 'Quarterly', '16/7/26', 'Renewal Pending', NULL, NULL, 'Sales POC following up on renewal, delay from cx, finance team delaying.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '17/4/2026', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Green', 'Stable account. Few implementations were self-implemented and need re-implementation.', 'Convinced cx to get the use cases reimplemented through partners.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Dr. Agarwal''s Health Care Limited', '58405', 'Healthcare and Wellness', 'Tier 2 (300k - 500k)', 474500, 'South', 'Anindya', 'Poorva Pandya', NULL, 'Mrinmoy Chakraborty', 'VLS Amrutha', 'Quarterly', '27/11/26', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '4/23/24', 'Yes', 'Yes', 'No', NULL, NULL, 'Amber', 'Account is stable, no major challenges reported. Any emerging risks will be flagged and addressed promptly.', NULL, 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Ecozen Solutions Private Limited', '74045', 'Business Services or B2B', 'Tier 1 (>500k)', 434693, 'West', 'Anindya', 'Nikhil Chand', '25-Apr-26', 'Rishit Hitesh Sheth', 'Abhinav', 'Quarterly', '31/12/26', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '14-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Delay in OMS; customization not in roadmap; delay in Service cloud delivery; MCP ETA not given.', 'OMS Forms and processes delivered; Phase 1 Service Cloud ETA pending; Pulse AI demo given.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('EDUTRA CONSULTING SERVICES PRIVATE LIMITED', '62216', 'Education', 'Tier 1 (>500k)', 1087200, 'North', 'Anindya', 'Abhishek Bhargav', '18-Apr-26', 'Shivam Singh', 'Santhosh', 'Quarterly', '30/04/26', 'Renewed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '15/4/2026', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Recent email and WA issues addressed via war room. Bot changes deployed awaiting go-ahead. Client shared potential data leakage.', 'Infosec team involved checking possible reasons for data leakage.', 'No', 'No', 100, NULL, NULL, NULL),
  ('Entri Software Pvt Ltd', '60234', 'Edtech', 'Tier 1 (>500k)', 663823, 'South', 'Anindya', 'Amarjeet', '18-Apr-26', 'Vijayakumar K', 'Madan', 'Quarterly', '8/9/26', 'Renewal Pending', NULL, NULL, 'No Risk, Ontrack to be renewed, OF being prepared.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '16/4/2026', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Green', 'POC is LeadSquared pro with hands-on experience. Major concern around Siera proactively addressed.', 'Proactive discussions with cx and product team to sort Siera issues.', 'No', 'No', 100, NULL, NULL, NULL),
  ('EVEN HEALTHCARE PRIVATE LIMITED', '76389', 'Healthcare and Wellness', 'Tier 1 (>500k)', 721835, 'South', 'Anindya', 'Poorva Pandya', NULL, NULL, 'VLS Amrutha', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Amber', 'Customer recently highlighted issues in getting prompt response from support and PS for CRs. CSM involved post April to maintain tracker.', NULL, 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Greenply Industries Ltd', '57771', 'Manufacturing', 'Tier 1 (>500k)', 542600, 'West', 'Anindya', 'Bhoomit Ahlawat', '18-Apr-26', 'Shikhar', 'Vardhan BO', 'Quarterly', '30/06/26', 'Renewal Pending', 'Churn Activated', 'Adoption', 'Churn Activated — Adoption. New tenant ready since 20 March 2026 but go-live stalled. Leadership transitions blocking power-user approval. UAT not initiated.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '2-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Red', 'Many issues in old implementation; slow adoption of new tenants; negative sentiment on SIERA migration; go-live stalled; leadership transitions blocking approvals.', 'Configured new tenant; running war room with PS/Dev/Reports/Support; Dynamic PJP GMS data push to S3; pushing customer to provide UAT power users.', 'No', 'Yes', 100, NULL, NULL, 'Open'),
  ('GupShup Technology India Pvt. Ltd.', '8287', 'Business Services or B2B', 'Tier 2 (300k - 500k)', 319000, 'West', 'Anindya', 'Nikhil Chand', '25-Apr-26', 'Vineet Pandey', 'No', 'Half Yearly', '17/08/26', 'Renewal Pending', NULL, NULL, 'No Renewal risk.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '23-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Primary use case is sending communications to partners through LSQ. Use case not sticky and can be a risk.', 'To connect with Cx to identify opportunities in week of 11-15th May.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('GUS Global Services India Private Limited', '58385', 'Education', 'Tier 2 (300k - 500k)', 321650, 'North', 'Anindya', 'Poorva Pandya', '4/14/26', 'Shivam Singh', 'No', 'Half Yearly', '27/01/28', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '4/23/26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Green', 'License utilisation 93%. Product stickiness using Converse, Bot, Mavis. Interested for SC pilot.', 'Active engagement with key stakeholders, QBR.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Guvi Geek Network Pvt Ltd', '50223', 'Edtech', 'Tier 1 (>500k)', 1206278, 'South', 'Anindya', 'Amarjeet', '18-Apr-26', 'Vijayakumar K', 'Vardhan BO', 'Quarterly', '7/8/26', 'Renewal Pending', NULL, NULL, 'Sales POC working actively with Cx for Renewal, no risk detected.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '24/4/2026', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Green', 'Stable account. Simple CR requests expedited proactively.', 'Simple CR requests are expedited from our end and solutions given proactively.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Hero MotoCorp Ltd.', '53732', 'Automotive', 'Tier 1 (>500k)', 1464745, 'North', 'Anindya', 'Bhoomit Ahlawat', '18-Apr-26', 'Anil/ Manish', 'Prakhar', 'Yearly', '4/12/26', 'Renewed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '27-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Green', 'Account stable. No major challenges reported.', 'Any emerging risks will be proactively flagged and addressed promptly.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Hindware', '62528', 'Business Services or B2B', 'Tier 2 (300k - 500k)', 319455, 'North', 'Anindya', 'Poorva Pandya', '18-Apr-26', 'Anjali Jha', 'No', 'Half Yearly', '31/03/2026', 'Renewal Pending', NULL, NULL, 'Renewal pending, no risk.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '4/7/26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'OMS built on custom setup; any change requires extensive coordination between SAP and LSQ teams causing frustration.', 'OMS demo completed. Evaluating feasibility of all edge cases before migrating to OMS.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('IIDE Education Private Limited', '63859', 'Education', 'Tier 2 (300k - 500k)', 300869, 'West', 'Anindya', 'Nikhil Chand', '18-Apr-26', 'Rishit Hitesh Sheth', 'Prakhar', 'Half Yearly', '11/5/26', 'Renewal Pending', 'Churn Activated', 'Experience', 'Renewal Risk. Cx not ready to renew unless platform problems are stabilized. PS audit raised.', NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', '10-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Red', 'Intermittent platform issues led to dissatisfaction. Cx looking at Salesforce as alternative.', 'Regular connect for solution consulting, issue resolution, follow up with support team for faster resolution.', 'Yes', 'Yes', 99, NULL, NULL, 'Open'),
  ('Imarticus Learning Pvt. Ltd.', '7764', 'Edtech', 'Tier 1 (>500k)', 608311, 'West', 'Anindya', 'Nikhil Chand', '18-Apr-26', 'Rishit Hitesh Sheth', 'Vardhan BO', 'Half Yearly', '9/4/26', 'Renewal Pending', NULL, NULL, 'BTL tenant is churned. Main tenant will be renewed. PS audit and reimplementation raised.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '26-Mar-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Cx considering new tenant for Singapore/Malaysia. BTL account churned as Cx developed in-house solution.', 'Connected with Aditya Swaroop and Amar Khavare to optimize batch job query. Regular engagement.', 'No', 'Yes', 100, NULL, NULL, 'Open'),
  ('International Tractors Limited', '62253', 'Automotive', 'Tier 1 (>500k)', 1000000, 'North', 'Anindya', 'Bhoomit Ahlawat', '18-Apr-26', 'Shikhar', 'Drushadwathi B Salian', 'Quarterly', '28/07/26', 'Renewal Pending', 'Churn Activated', 'Experience', 'Churn Activated — Experience. Man-days approval blocked over a year. Large field-sales forms reducing adoption. Solis in-house CRM risk.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '2-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Red', 'Customer rarely approves efforts; large field-sales forms; TMS↔LSQ integration gaps; mobile dashboards pending; Solis in-house CRM risk; 10-ticket escalation raised to LSQ leadership.', 'Working with McKinsey to increase stickiness; WA campaigning; delivering call-centre reports; McKinsey integration scope finalized at 7 LSQ man-days.', 'No', 'Yes', 100, NULL, NULL, 'Open'),
  ('Jain University', '66807', 'Education', 'Tier 2 (300k - 500k)', 308227, 'South', 'Anindya', 'Vaibhav', '18-Apr-26', 'Anurag Choudhary', 'Vardhan BO', 'Quarterly', '28/11/2026', 'Renewal Pending', NULL, NULL, NULL, NULL, NULL, 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', NULL, NULL, 'Green', 'Publisher Panel data mismatching or onboarding delays. System stable across all tenants. Last renewal had competition concern, pricing revised.', 'Initiated regular calls, sorted PP issues, helped with Telephony and AI Bot integrations. MRR lowered to retain client.', 'Yes', 'No', 80.91, NULL, NULL, 'Open'),
  ('Jaro Toppscholars Private Limited', '38288', 'Edtech', 'Tier 1 (>500k)', 965250, 'West', 'Anindya', 'Nikhil Chand', '18-Apr-26', 'Khushi Arora', 'Santhosh', 'Quarterly', '15/06/26', 'Renewal Pending', 'Churn Activated', 'Adoption', 'Renewal Risk. Cx not ready to renew unless working solution of reimplementation is available. In person meeting between Jaro and LSQ management done.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '8-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Red', 'Competitor Risk: Zoho due to CTO change. Old implementation not per industry standards. Data points not captured properly. Unnecessary opportunity fields exhausted field limit.', 'Reimplementation ongoing with Phase 1 demo done. Testing at Cx end. Phase 2 workshop after Phase 1 rollout.', 'No', 'Yes', 100, NULL, NULL, 'Open'),
  ('Knowledgehut Solutions Pvt Ltd', '5291', 'Edtech', 'Tier 1 (>500k)', 583802, 'South', 'Anindya', 'Abhishek Bhargav', '25-Apr-26', 'Vijayakumar K', 'Manisha', 'Quarterly', '1/7/28', NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', '9-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Green', 'Stable account, no major issues. Subsidiary of upGrad. Recent changes needed in forms, stages and dispositions.', 'Requirement checked and discussed in detail with client. Changes to be made per requirement shared.', 'Yes', 'No', 99, NULL, NULL, 'Open'),
  ('Lakshya Internet Private Limited', '35931', 'Business Services or B2B', 'Tier 1 (>500k)', 683873, 'North', 'Anindya', 'Bhoomit Ahlawat', '18-Apr-26', 'Shikhar', 'No', 'Quarterly', '20/10/26', NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', '3-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'All 3 tenants have good usage. Customer does not raise multiple tickets.', 'Met customer F2F and set up weekly cadence; sat with end users to observe how they use LSQ.', 'Yes', 'No', 97, NULL, NULL, 'Open'),
  ('Learnfluence Education Private Limited', '55343', 'Education', 'Tier 1 (>500k)', 686209, 'East', 'Anindya', 'Abhishek Bhargav', '18-Apr-26', 'Vijayakumar K', 'No', 'Quarterly', '11/3/27', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '9/4/26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'LinkedIn connector facing gap where capture activity not supported. Field data received but not captured on lead.', 'Request raised to support and EVPS MS team to make the required changes.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Leverage Ed-Tech Pvt Ltd.', '50698', 'Edtech', 'Tier 1 (>500k)', 1368634, 'North', 'Anindya', 'Abhishek Bhargav', '18-Apr-26', 'Shivam Singh', 'No', 'Quarterly', '17/11/26', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '9/4/26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Green', 'Implementations ongoing and client not facing any burning issues. One issue with field addressed.', 'Support team checking the issue with EVPS MS team for lead/opp field update issue.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Life Cell International Pvt Ltd', '56176', 'Healthcare and Wellness', 'Tier 2 (300k - 500k)', 300140, 'South', 'Anindya', 'Vaibhav', '25-Apr-26', 'Mrinmoy Chakraborty', 'No', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '20/04/2026', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Green', 'No major changes. Client usage is good, account is stable.', 'Regular connect and weekly calls ensuring no query or concern is missed.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Locon Solutions Private Limited', '64107', 'Real Estate', 'Tier 1 (>500k)', 1794125, 'West', 'Anindya', 'Bhoomit Ahlawat', '18-Apr-26', 'Shikhar', 'Madhu Kumar AN', 'Quarterly', '3/5/26', 'Renewal Pending', 'Churn Activated', 'Adoption', 'Active Ring Fence account. Renewal pending. Likely to renew. Committed reports not delivered — customer moved to internal reporting and renewed 1 year instead of 3.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '2-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Red', 'LSQ↔Lookup integration unstable; Order Management never operationalised; Owner data sync not fully fixed; BRD audit demanded; new requirements paused.', 'Delivered FSE Reimbursement & Sales Connect V2 reports; Owner Mismatch escalated P0; replaced DRM with senior PS SPOC; weekly war room running.', 'No', 'Yes', 100, NULL, NULL, 'Open'),
  ('Mad About Sports OPC Pvt Ltd', '68986', 'Edtech', 'Tier 1 (>500k)', 1343700, 'East', 'Anindya', 'Amarjeet', '18-Apr-26', 'Mrinmoy Chakraborty', 'VLS Amrutha', 'Quarterly', '21/05/26', 'Renewed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '24/4/2026', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Escalation about product features and integrations. Sales CRM fine, problem is Service Cloud feature requests.', 'Mapped consolidated issues, taking progressive actions. Introduced CloneDB for customer use cases.', 'No', 'Yes', 100, NULL, NULL, 'Open'),
  ('MAKE MY TRIP (INDIA) PVT LTD', '76247', 'Business Services or B2B', 'Tier 2 (300k - 500k)', 333082, 'North', 'Anindya', 'Poorva Pandya', NULL, 'Anil/ Manish', 'Prakhar', 'Quarterly', '31/03/26', 'Renewal Pending', NULL, NULL, 'Renewal pending, MSA under discussion with legal, no risk.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '4/2/26', 'Yes', 'Yes', 'No', NULL, NULL, 'Amber', 'Stickiness low; only half the team using LSQ. Existing report of no use. They export data to Excel and create reports on BI.', 'Discovery call on 6th May. Working on reports and dashboards per their use case. Awaiting report formats.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Manipal Health Enterprises Pvt Ltd', '49983', 'Healthcare and Wellness', 'Tier 1 (>500k)', 2105066, 'South', 'Anindya', 'Amarjeet', '18-Apr-26', 'Mrinmoy Chakraborty', 'VLS Amrutha', 'Half Yearly', '7/11/28', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '16/4/2026', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Product limitations impacting expectations. Multiple Mobile Application issues unresolved for a long time despite multiple discussions.', 'Feasibility discussions initiated with Product. Workarounds provided till product feature is developed.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('MAXIMISED QUALIFIED LEADS LLP', '73907', 'Marketing Agency', 'Tier 2 (300k - 500k)', 333700, 'West', 'Anindya', 'Poorva Pandya', NULL, 'Rishit Hitesh Sheth', 'No', 'Quarterly', '13/10/26', NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', '4/24/26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Stickiness less; using only for channel partners, not own sales team. Re-implementation discussion ongoing.', 'Implemented Route Mobile, Mcube and Converse to increase stickiness.', 'Yes', 'No', 59, NULL, NULL, NULL),
  ('Medanta The Medicity', '76424', 'Healthcare and Wellness', 'Tier 2 (300k - 500k)', 466628, 'North', 'Anindya', 'Poorva Pandya', '4/15/26', 'Shikhar', 'VLS Amrutha', 'Quarterly', '31/03/28', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '21-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Management concern about lack of visibility of genuine field visits. Incorrect average field visits data.', 'Suggested enabling geo-fencing to restrict users marking task at doctor location. Report changes needed.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('MILES EDUCATION PRIVATE LIMITED', '66203', 'Education', 'Tier 2 (300k - 500k)', 309650, 'South', 'Anindya', 'Vaibhav', '25-Apr-26', 'Shivam Singh', 'No', 'Half Yearly', '1/6/28', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', NULL, NULL, 'Green', 'Usage good and account stable. Recently purchased CloneDB for PowerBI dashboards.', 'Regular connect ensuring no delay in queries and concerns, adding client confidence.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Motion Education Private Limited', '52794', 'Education', 'Tier 1 (>500k)', 626655, 'North', 'Anindya', 'Vaibhav', '18-Apr-26', 'Shivam Singh', 'No', 'Quarterly', '23/5/26', 'Renewal Pending', NULL, NULL, 'Renewal pending, no risk.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', NULL, NULL, 'Green', 'Renewal processed with slight contraction as Cx removed Zip teams. New features shared for Channel Partner case to increase user count.', NULL, 'No', 'No', 100, NULL, NULL, 'Open'),
  ('NOGUILT FITNESS & NUTRITION INDIA PRIVATE LIMITED (Fitelo)', '51685', 'Healthcare and Wellness', 'Tier 1 (>500k)', 676823, 'North', 'Anindya', 'Abhishek Bhargav', '18-Apr-26', 'Shikhar', 'No', 'Quarterly', '31/03/26', 'Renewed', 'Churn Activated', 'Experience', NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', '31-03-2026', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'WA converse and lead deletion issues addressed on priority. No open pointers currently.', 'Planning meet with CBO at their office. Deletion process ongoing. WA conversations added as FOC.', 'Yes', 'Yes', 52, NULL, NULL, 'Open'),
  ('Outleap Technologies Private Limited', '53546', 'Lending', 'Tier 1 (>500k)', 667800, 'South', 'Anindya', 'Vaibhav', NULL, 'Abhishek Kumar', 'No', 'Half Yearly', '30/09/26', 'Renewal Pending', NULL, NULL, 'Renewal pending, no risk.', NULL, NULL, 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', '11-May-26', 'Yes', 'Yes', 'No', NULL, NULL, 'Green', 'Account stable. Ex-LSQ PS managing CRM. Low support incidents. GRR reduced 7% due to international finance business closure from geopolitical situation.', 'Continue weekly Cadence calls to maintain Green status.', 'Yes', 'No', 93, NULL, NULL, 'Open'),
  ('PagarBooks (GyanKaar Technologies Pvt. Ltd)', '48888', 'Business Services or B2B', 'Tier 1 (>500k)', 717600, 'South', 'Anindya', 'Amarjeet', '27-Apr-26', 'Anjali Jha', 'No', 'Quarterly', '18/04/26', 'Renewal Pending', 'Churn Activated', 'Commercial', 'Cx did not renew, wants to include Zipteams in MRR, lead export activity noticed in bulk.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '7-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Red', 'Price issue, not renewed. Exported leads in bulk. Want Zipteams included in price without extra payment.', 'Trying to mitigate at management level.', 'No', 'Yes', 100, NULL, NULL, NULL),
  ('Phasorz Technologies Private Limited', '60857', 'Healthcare and Wellness', 'Tier 1 (>500k)', 650180, 'South', 'Anindya', 'Amarjeet', '1-Jun-26', 'Mrinmoy Chakraborty', 'No', 'Quarterly', '26/05/26', 'Renewal Pending', NULL, NULL, 'Sales POC confirming renewal today. Want to explore AI capability challenges - offered Invorto + Zipteams.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'No', 'Yes', 'No', NULL, NULL, 'Amber', 'Stable account, no major issues. Low support tickets. Guiding new PoC who recently took over from old outgoing PoC.', 'Continue weekly Cadence calls. Guiding new PoC.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Physics Wallah Pvt. Ltd.', '76244', 'Edtech', 'Tier 1 (>500k)', 6462580, 'North', 'Anindya', 'Vaibhav', '18-Apr-26', 'Vijayakumar K', 'Madan', 'Quarterly', '15/2/2028', 'Renewal Pending', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '16/04/2026', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Green', 'Support queries and feature requests delayed due to multiple TAM changes, causing backlog in resolution.', 'All open support tickets consolidated in centralized tracker. Multiple POC meetings underway.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Practo Technologies Private Limited', '33121', 'Healthcare and Wellness', 'Tier 1 (>500k)', 588980, 'South', 'Anindya', 'Vaibhav', NULL, 'Mrinmoy Chakraborty', 'VLS Amrutha', 'Quarterly', '4/1/27', 'Renewed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'No', 'Yes', 'No', NULL, NULL, 'Amber', 'Stable account, mostly self implemented. 21 support tickets in last 30 days, most related to system downtime.', 'Setting up weekly cadence to discuss open issues and assist.', 'No', 'No', 100, NULL, NULL, NULL),
  ('Prasad Demo', '78622', 'Education', 'Tier 2 (300k - 500k)', 330670, 'North', 'Anindya', 'Poorva Pandya', '4/16/26', 'Anil/ Manish', 'No', 'Quarterly', '29/10/26', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'No', 'No', 'No', NULL, NULL, 'Green', 'No major issues. Utilisation 100%. Product stickiness using Converse, Connectors, Bot.', 'Active engagement with key stakeholders, QBR.', 'No', 'No', 100, NULL, NULL, NULL),
  ('Prayosha Food Services Pvt. Ltd', '54698', 'Business Services or B2B', 'Tier 1 (>500k)', 570606, 'West', 'Anindya', 'Nikhil Chand', '18-Apr-26', 'Anil/ Manish', 'Amit', 'Half Yearly', '26/04/28', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '30-Mar-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Red', 'Delay in Reimplementation going live. Payment webhook placement pending at Cx end. User creation and Data migration pending.', 'Followed up with Cx for payment webhook placement and asked Cx to create users in new tenant.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Prepladder Private Limited', '76590', 'Edtech', 'Tier 2 (300k - 500k)', 322404, 'North', 'Anindya', 'Poorva Pandya', NULL, 'Vineet Pandey', 'Prakhar', 'Quarterly', '29/11/26', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '4/1/26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Acquired by Unacademy. They have own CRM system. Chandigarh team laid off, operations shifting to Bangalore. Foreseeable churn risk.', 'System heavily dependent on LSQ. Ensuring no delay in support resolution. High engagement with key stakeholders.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Prestige Holiday Resorts LLP (Karma Group)', '39752', 'Travel and Hospitality', 'Tier 1 (>500k)', 789855, 'South', 'Anindya', 'Vaibhav', '18-Apr-26', 'Mrinmoy Chakraborty', 'No', 'Quarterly', '30/09/28', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '13/04/2026', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Red', 'Reports and dashboards concern raised. Cx needs multiple AI features and exploring market for same.', 'Lead Capture issue resolved by configuring Phone and Email as non-unique fields. Distribute Card limit workaround shared.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('PRISM JOHNSON LIMITED', '76287', 'Manufacturing', 'Tier 1 (>500k)', 530926, 'North', 'Anindya', 'Bhoomit Ahlawat', '18-Apr-26', 'Rishit Hitesh Sheth', 'Prakhar', 'Quarterly', '10/7/27', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '1-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Red', 'Initial scope not yet delivered; Dealer/Non-Trade team onboarding slower than expected; multiple PS SPOC churns called out.', 'Running war room with PS/Dev/Reports/Support; F2F visit (19-20 May) produced 97-item tracker; Retailer Onboarding BRD signed off.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Proptiger Marketing Services Private Limited', '62854', 'Real Estate', 'Tier 1 (>500k)', 1149422, 'North', 'Anindya', 'Bhoomit Ahlawat', '18-Apr-26', 'Shikhar', 'Madhu Kumar AN', 'Quarterly', '26/05/28', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '8-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Shared Lookup root issues with Housing — LSQ↔Lookup integration instability, report/call-data mismatch, OMS dual-system usage, owner-sync pending.', 'Delivered FSE Reimbursement & Sales Connect V2 reports; Owner Mismatch P0 escalated; BRD audit underway.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Qift Solutech Private Limited', '61110', 'Edtech', 'Tier 1 (>500k)', 849983, 'South', 'Anindya', 'Amarjeet', '25-Apr-26', 'Vijayakumar K', 'No', 'Monthly', '31/08/26', 'Renewal Pending', NULL, NULL, 'Sales POC working actively with Cx for Renewal, no risk detected.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '10/4/26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Green', 'Proactive cadence with all POCs in place. Measures taken to prevent further contraction.', 'Process corrections, reporting changes, and configuration recommendations shared.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Quality Care India Limited', '76673', 'Healthcare and Wellness', 'Tier 2 (300k - 500k)', 423550, 'South', 'Anindya', 'Vaibhav', '18-Apr-26', 'Shikhar', 'No', 'Quarterly', '12/9/27', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '10/4/26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Calling Metrics mismatch on Opportunities. Call Session ID not updating consistently causing discrepancy between LSQ and TechM records.', 'Regular calls scheduled with client and EVPS to track and resolve concerns.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Quantinsti Quantitative Learning Pvt Ltd', '13692', 'Edtech', 'Tier 2 (300k - 500k)', 405376, 'West', 'Anindya', 'Poorva Pandya', NULL, 'Rishit Hitesh Sheth', 'No', 'Quarterly', '28/02/26', NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', '4/24/26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Green', 'No major issues. Minor support issues only. Adoption good. Team is pro LSQ.', 'Active engagement with key stakeholders, QBR, Product demo.', 'Yes', 'No', 77, NULL, NULL, 'Open'),
  ('Rainbow Hospital', '79190', 'Edtech', 'Tier 1 (>500k)', 0, 'South', 'Anindya', 'Abhishek Bhargav', NULL, 'Siddharth Menon', 'No', 'Yearly', '9/1/29', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', NULL, NULL, NULL, 'Yes', 'Yes', NULL, NULL, 'Red', 'Account under implementation. Website integrations and Ozonetel are serious concerns. New website integration requirements shared.', 'Connecting with client on daily cadence call and working to close all pointers.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Rankguru Technology Solutions Private Limited', '54664', 'Edtech', 'Tier 1 (>500k)', 1414500, 'South', 'Anindya', 'Nikhil Chand', '25-Apr-26', 'Anjali Jha', 'Santhosh', 'Quarterly', '30/09/26', 'Renewal Pending', NULL, NULL, 'No renewal risks. Consolidated Renewal of 4 tenants on 30 June 2026. Cx concerned about recent downtimes and charged CRs.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '16-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Project Build expected 30 May, PS ETA 22 June. Missing PJP reports. Historical data mismatch. OMS issues.', 'Weekly Cadence in place. Exploring option to go back to sync API.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Scholiverse Educare Private Limited', '62410', 'Edtech', 'Tier 2 (300k - 500k)', 363378, 'North', 'Anindya', 'Poorva Pandya', '4/14/26', 'Shivam Singh', 'No', 'Yearly', '22/01/27', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '4/22/26', 'Yes', 'Yes', 'No', NULL, NULL, 'Red', 'Acquired by UpGrad. Planning to shut down PGC vertical as it may cannibalize UpGrad''s offerings. Downgrade expected in July. Foreseeable churn risk.', 'Discussion ongoing to mitigate contraction.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('STERLING HOLIDAY RESORTS LIMITED', '69382', 'Travel and Hospitality', 'Tier 2 (300k - 500k)', 350850, 'South', 'Anindya', 'Vaibhav', '18-Apr-26', 'Mrudhula Purushottam', 'No', 'Quarterly', '8/4/27', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '15/4/2026', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Client raised concern about ZIP teams delay and incomplete SOW despite being billed from start.', 'CP connecting with client regarding ZIP Teams charges. Initiated regular calls for queries and concerns.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('STUDYIQ Education Pvt. Ltd.', '63985', 'Edtech', 'Tier 1 (>500k)', 703300, 'North', 'Anindya', 'Abhishek Bhargav', NULL, 'Shivam Singh', 'No', 'Quarterly', '11/9/26', 'Renewal Pending', 'Churn Predicted', 'Commercial', 'Client undergoing internal restructuring, has pending dues, preparing for IPO. Cost-optimization review underway.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '6/4/26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Red', 'Invorto AI bot demo given but no dates for further discussion. 2 tenants churned, 1 remaining. Payments due. Business slowdown.', 'Need to implement AI bot asap and consult for other products and workflows.', 'No', 'Yes', 100, NULL, NULL, NULL),
  ('Sunrise Mentors Pvt Ltd', '46711', 'Edtech', 'Tier 1 (>500k)', 633350, 'North', 'Anindya', 'Abhishek Bhargav', '18-Apr-26', 'Siddharth Nair', 'No', 'Quarterly', '16/09/26', 'Renewal Pending', NULL, NULL, 'Account health is green, do not see any risk.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '9/4/26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Green', '92% logins and 22% increase in automation usage. Siera used extensively.', 'Regular touch with client teams sharing latest product updates.', 'No', 'No', 100, NULL, NULL, NULL),
  ('Symphony Limited', '47236', 'Manufacturing', 'Tier 2 (300k - 500k)', 318892, 'North', 'Anindya', 'Poorva Pandya', '18-Apr-26', 'Rishit Hitesh Sheth', 'Santhosh', 'Quarterly', '25/05/26', NULL, 'Churn Executed', 'Commercial', NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', NULL, 'No', 'No', 'No', NULL, NULL, 'Red', 'Poor SIERA Migration planning. 7 HODs unable to fetch report for MD visibility for 25 days. Cx wanted lesser commercials.', 'Providing data dump but customer expected everyday reports.', 'Yes', 'Yes', 0, NULL, NULL, 'Churn'),
  ('TopRankers', '12357', 'Edtech', 'Tier 1 (>500k)', 517397, 'South', 'Anindya', 'Abhishek Bhargav', '18-Apr-26', 'Anjali Jha', 'Madan', 'Quarterly', '3/6/26', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '14-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Account mostly self-implemented, causing disturbances in automation execution. Customer sentiment low due to recurring issues.', 'Managed Services discussion in-progress. Weekly cadence call to reduce TAT on open issues and train Cx PoC.', 'No', 'No', 100, NULL, NULL, NULL),
  ('Toyota Kirloskar Motor Private Limited', '73680', 'Automotive', 'Tier 1 (>500k)', 1290210, 'South', 'Anindya', 'Amarjeet', '27-Apr-26', 'Mohammed Ali Azhar', 'VLS Amrutha', 'Yearly', '30/04/27', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'No', 'Yes', 'Yes', NULL, NULL, 'Green', 'DRM account. Nothing major highlighted.', 'Continue weekly Cadence calls to maintain Green status.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('TUTOPIA PRIVATE LIMITED', '78213', 'Edtech', 'Tier 2 (300k - 500k)', 410800, 'East', 'Anindya', 'Amarjeet', '18-Apr-26', 'Mrinmoy Chakraborty', 'Amit', 'Quarterly', '24/07/28', 'Renewal Pending', 'Churn Activated', 'Adoption', 'Adoption is primary issue. In-house CRM competitor.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '9/4/26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Red', 'Adoption issue. CSM deployed on site. POC change and scope creep. No CSM for 3 months. SIERA Migration impacted live reports.', 'Leadership engagement, roadmap discussions, value demonstrations, stickiness initiatives driven proactively.', 'No', 'Yes', 100, NULL, NULL, 'Open'),
  ('Unext Learning Private Limited', '54036', 'Edtech', 'Tier 1 (>500k)', 2891100, 'South', 'Anindya', 'Amarjeet', '18-Apr-26', 'Vijayakumar K', 'Madhu Kumar AN', 'Yearly', '31/03/26', 'Renewed', NULL, NULL, NULL, NULL, NULL, 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', '6/4/26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Green', 'Integration issues or dependency delays impacting project progress.', 'Dependencies identified, customer and internal stakeholders followed up with, technical teams aligned.', 'Yes', 'No', 90.65, NULL, NULL, 'Open'),
  ('upGrad Education Private Limited', '49074', 'Edtech', 'Tier 1 (>500k)', 3852789, 'South', 'Anindya', 'Abhishek Bhargav', '25-Apr-26', 'Vijayakumar K', 'Manisha', 'Quarterly', '19/09/26', 'Renewal Pending', NULL, NULL, 'Account health remains Green. A few new CRs currently under development. No significant risks identified.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '9-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'High volume of open consultation and solutioning requests. Customer heavily reliant on LSQ support. Delays on certain integrations driven by internal customer processes.', 'Weekly Cadence call setup and regular updates on all open CRs being provided.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('VALOREM STACK PRIVATE LIMITED', '63074', 'Banks', 'Tier 1 (>500k)', 628000, 'South', 'Anindya', 'Nikhil Chand', '27-Apr-26', 'Khushi Arora', 'No', 'Quarterly', '2/9/26', 'Renewal Pending', NULL, NULL, 'Support ticket resolution takes too much time. Renewal risk minimum per current CP.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '21-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Stable account. Quite a few tickets related to Service Cloud, Chatbot or Reporting.', 'Chatbot and Service Cloud adoption good. One open ticket pending with Engineering team.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('VDK Eduventures Pvt Ltd', '51122', 'Edtech', 'Tier 1 (>500k)', 613006, 'North', 'Anindya', 'Abhishek Bhargav', '18-Apr-26', 'Shivam Singh', 'No', 'Quarterly', '8/8/26', 'Renewal Pending', NULL, NULL, 'No Risk, Ontrack to be renewed, OF being prepared.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '16/4/2026', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Green', 'Login 98% and execution persistently increasing. Client using Siera dashboard with good understanding of LSQ.', 'Regular touch with client teams sharing latest product updates.', 'No', 'No', 100, NULL, NULL, NULL),
  ('VEDANTU INNOVATIONS PRIVATE LIMITED', '70970', 'Edtech', 'Tier 1 (>500k)', 1476022, 'South', 'Anindya', 'Vaibhav', '27-Apr-26', 'Anjali Jha', 'Santosh', 'Quarterly', '11/9/28', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '20-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Green', 'Account stable. No major challenges reported.', 'Weekly Cadence set up for ad-hoc issues and regular touchpoints.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Vidyakul Learning Space Private Limited', '55996', 'Edtech', 'Tier 2 (300k - 500k)', 430636, 'North', 'Anindya', 'Poorva Pandya', '4/13/26', 'Shivam Singh', 'No', 'Quarterly', '24/09/27', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '4/22/26', 'Yes', 'Yes', 'No', NULL, NULL, 'Green', 'No major issues. Utilisation 100%. Product stickiness using Converse, Connectors, Bot.', 'Active engagement with key stakeholders, QBR.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Vidyashilp School', '51472', 'Education', 'Tier 3 (200k - 300k)', 243848, 'South', 'Anindya', 'Amarjeet', '18-Apr-26', 'Mrudhula Purushottam', 'No', 'Quarterly', '3/7/27', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '2/4/26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Delays observed in implementation, PS delivery, support resolution, or pending committed deliverables.', 'Regular follow-ups initiated with PS, Support, Product, and DRM teams.', 'No', 'No', 100, NULL, NULL, NULL),
  ('VRINDAYARDS SOLUTIONS PRIVATE LIMITED (Hero Vired)', '76366', 'Business Services or B2B', 'Tier 2 (300k - 500k)', 428650, 'North', 'Anindya', 'Poorva Pandya', '4/13/26', 'Shivam Singh', 'No', 'Half Yearly', '14/05/28', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '4/23/26', 'Yes', 'Yes', 'No', NULL, NULL, 'Amber', 'After reimplementation to lead module, account settled. No major issues but they are building their own CRM - churn risk.', NULL, 'No', 'No', 100, NULL, NULL, 'Open'),
  ('WHEELSEYE LOGISTICS PRIVATE LIMITED', '68685', 'Logistics', 'Tier 1 (>500k)', 981330, 'North', 'Anindya', 'Bhoomit Ahlawat', '18-Apr-26', 'Rishit Hitesh Sheth', 'Prakhar', 'Quarterly', '1/10/26', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '7-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'New tenant went live, needed hand-holding to increase usage. Reports feasibility issues.', 'Solved queries/issues for newly live tenant; raised product feature requests; weekly cadence set up; swift replies.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Xanadu Realty Private Limited', '50486', 'Real Estate', 'Tier 1 (>500k)', 558801, 'West', 'Anindya', 'Nikhil Chand', '18-Apr-26', 'Anil/ Manish', 'Madhu Kumar AN', 'Quarterly', '9/12/26', 'Renewal Pending', NULL, NULL, 'Account health is green, do not see any risk.', NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '9-Apr-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Delay in delivery of new tenant flows. Out of 5 flows, only pre-sales flow near completion. Invorto bot delay.', 'Regular follow up with DRM. Consulting with Brijendra to unblock UDS errors. Meeting set with Invorto team for ETA.', 'No', 'No', 100, NULL, NULL, 'Open'),
  ('Zell Education LLP', '37705', 'Edtech', 'Tier 1 (>500k)', 560500, 'West', 'Anindya', 'Nikhil Chand', '18-Apr-26', 'Rishit Hitesh Sheth', 'No', 'Yearly', '12/1/27', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', '26-Mar-26', 'Yes', 'Yes', 'Yes', NULL, NULL, 'Amber', 'Multiple support tickets ongoing. Prominent ones are Converse, Service Cloud, UDS. Features don''t work as intended or new feature requests raised.', 'Connected with Managed Services team for UDS logic update. Regular connect for solution consulting and issue resolution.', 'No', 'No', 100, NULL, NULL, 'Open');
